name: Docker Prepare image

on:
  push:
    branches:
      - deployment
  pull_request:
    types:
      - closed
    branches:
      - deployment

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_DEV_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_DEV_PASSWORD }}
  TAG_NAME: ${{ secrets.DEV_TAG_NAME}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t $DOCKER_USERNAME/$TAG_NAME:latest .

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD"

      - name: Push to Docker Hub
        run: docker push $DOCKER_USERNAME/$TAG_NAME:latest
