name: Run Tests

on:
  pull_request:
    branches:
      - main

env:
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
  TWITTER_TOKEN: ${{ secrets.TWITTER_API_SECRET }}
  LIX_API_KEY: ${{ secrets.LIX_API_KEY }}
  PALM_API_KEY: ${{ secrets.PALM_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |
          python -m venv env
          pip install poetry
          poetry lock
          poetry install
          ./setup.sh

      - name: Wait for API to be ready
        run: |
          while ! curl -sSf http://localhost:8000 > /dev/null; do
            echo "Waiting for API to be ready..."
            sleep 5
          done
          echo "API is ready!"

      - name: Run tests
        run: |
          poetry run pytest --tb=short --disable-warnings -q

      - name: Deactivate Virtual Environment
        if: always()
        run: |
          deactivate || echo "Deactivation not needed for this setup"
