name: Run RAG evaluation tests
on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

env:
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
  TWITTER_TOKEN: ${{ secrets.TWITTER_API_SECRET }}
  LIX_API_KEY: ${{ secrets.LIX_API_KEY }}
  PALM_API_KEY: ${{ secrets.PALM_API_KEY }}

jobs:
  test:
    name: Perform RAG Evaluation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.6'


      - name: Install Poetry
        run: pip install poetry

      - name: Create and activate Virtual Environment
        run: poetry shell

      - name: Install requirements
        run: poetry install

      - name: Run tests(Rule-Based Evaluation)
        if: github.event_name == 'push'
        run: pytest test_rule_based_eval.py

      - name: Run tests(Model-Graded Evaluation)
        if: github.event_name == 'pull_request'
        run: pytest test_model_graded_eval.py

    strategy:
      fail-fast: true
