name: Run RAG evaluation tests
on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Perform RAG Evaluation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.6'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run tests(Rule-Based Evaluation)
        if: github.event == 'push'
        run: pytest test_rule_based_eval.py

      - name: Run tests(Model-Graded Evaluation)
        if: github.event == 'pull_request'
        run: pytest test_model_graded_eval.py

    strategy:
      fail-fast: true
